### ISSUE TITLE
Vega-lite chart component styling is inconsistent with the library

### ISSUE THREAD

**Issue by Shiti** [rustic-ai/ui-components#151]
**Describe the bug**
The vega-lite chart component's styling is inconsistent with the library. The options menu, axis-labels, font used in the charts, tooltip, etc do not align with ui-components.

**Expected behavior**
1. The menu options dropdown should use the same styling as the popover menu component. 
2. The label for the axis should be clearly visible. 
3. The font should be same as the one used within the app
4. The menu options should not hide the legend
5. The chart tooltip should follow the style of the library
6. The menu options tooltip should follow the style of the library

**Screenshots**
![Screenshot from 2024-05-20 12-27-54](https://github.com/rustic-ai/ui-components/assets/930312/1714e66a-937c-4552-b6b1-3927782b969a)

![Screenshot from 2024-05-20 12-28-19](https://github.com/rustic-ai/ui-components/assets/930312/b275814f-1220-4d75-ab7a-21489f01b2ac)

![Screenshot from 2024-05-20 14-14-49](https://github.com/rustic-ai/ui-components/assets/930312/fe7e40e9-e55b-4f05-8982-41ca8e709c4c)

**Please complete the following information:**
- Version of the library: 0.0.12

**Comment by lyjeileen** [comment]
Close as completed:

- https://github.com/rustic-ai/ui-components/pull/153
- https://github.com/rustic-ai/ui-components/pull/157
- https://github.com/rustic-ai/ui-components/pull/159
- https://github.com/rustic-ai/ui-components/pull/181
