### ISSUE TITLE
Calendar Text Styling

### ISSUE THREAD

**Issue by Laurendragonscale** [rustic-ai/ui-components#249]
**Describe the bug**
Looks like the styling is not aligned with the calendar component.

**Current**
<img width="496" alt="Screenshot 2024-07-26 at 1 34 13 PM" src="https://github.com/user-attachments/assets/a7377b85-b022-47e4-98b5-5a440873c105">

**Design**
<img width="239" alt="Screenshot 2024-07-26 at 1 43 04 PM" src="https://github.com/user-attachments/assets/6898d69e-498b-42e1-96ba-3a5afaa65e0b">

**Request to update**
Can we set a limit to the number of characters that will display before being cut off as outlined in the designs?

**Comment by kaseyvee** [comment]
Resolved in PR #256.
