### ISSUE TITLE
Emoji picker of textinput making too many network requests

### ISSUE THREAD

**Issue by kaseyvee** [rustic-ai/ui-components#261]
**Describe the bug**
The emoji picker in `TextInput` making too many network requests.

**To Reproduce**
See network tab in dev tools. See multiple `data.json` requests.
<img width="699" alt="Screenshot 2024-08-26 at 5 04 42 PM" src="https://github.com/user-attachments/assets/7562c651-9e8b-4822-a618-c5f1baf92123">

**Expected behavior**
This should be as reduced as possible.

**Screenshots**

**Please complete the following information:**

- Version of the library: 0.0.22

**Comment by Shiti** [comment]
fixed in [v0.0.23](https://github.com/rustic-ai/ui-components/releases/tag/v0.0.23)
