### ISSUE TITLE
Update icon size

### ISSUE THREAD

**Issue by Laurendragonscale** [rustic-ai/ui-components#95]
**Describe the bug**
Incorrect icon size. The icons used here should all be 32x32px in size. Looks like they are only 24x24px in size. 

**Expected behavior**
Should be 32px x 32px 
![Property 1=Volume Active, Property 2=Light](https://github.com/rustic-ai/ui-components/assets/142948108/c56617a8-4180-4c4b-9fce-49d2885f40aa)

**Screenshots**
![Screenshot 2024-04-25 at 2 38 38 PM](https://github.com/rustic-ai/ui-components/assets/142948108/d9eed13d-3032-47c0-98d9-eb7d15111881)

![Screenshot 2024-04-25 at 2 38 20 PM](https://github.com/rustic-ai/ui-components/assets/142948108/2ab28cb8-b2bb-4dd9-957b-ce163cd8457f)

**Comment by kaseyvee** [comment]
@Laurendragonscale Is it intentional that the sizes for these icons are different for the Video and Sound components? They are 24px on the Video component on Figma. Just want to confirm.

**Comment by Shiti** [comment]
@kaseyvee I think the size should be updated for both the media components.
