### ISSUE TITLE
Updates to sound bar colors.

### ISSUE THREAD

**Issue by Laurendragonscale** [rustic-ai/ui-components#96]
**Describe the bug**
Updates to sound bar colors. 

**To Reproduce**
1. playing: SECONDARY MAIN
2. loaded: ACTION/SELECTED
3. bar: ACTION/FOCUS

**Expected behavior**
![Property 1=Volume Active, Property 2=Light](https://github.com/rustic-ai/ui-components/assets/142948108/d2180e0d-2548-49a7-83ba-1cbba9c63295)

<img width="699" alt="Screenshot 2024-04-25 at 3 05 49 PM" src="https://github.com/rustic-ai/ui-components/assets/142948108/b04f61e8-ec2a-413d-94f3-f8e23fe27e45">

**Current behavior:**
![Screenshot 2024-04-25 at 2 38 20 PM](https://github.com/rustic-ai/ui-components/assets/142948108/9edbe54d-8118-4055-b594-285aef2c8419)

![Screenshot 2024-04-25 at 3 09 50 PM](https://github.com/rustic-ai/ui-components/assets/142948108/6be6b435-4c43-438a-81f6-5e552cd97860)

**Additional context**
Please refer to figma library

**Comment by lyjeileen** [comment]
Looks like the video progress bar has different colors in Figma. Do you want to use the same colors for sound and video component?

**Comment by Shiti** [comment]
@lyjeileen I think the colors mentioned here should be applied to both audio and video media components
